import { Component, inject, OnInit, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { PrimeNG } from 'primeng/config';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.html',
})
export class App implements OnInit {
  private readonly primeng = inject(PrimeNG);
  protected readonly title = signal('default');

  ngOnInit(): void {
    this.primeng.ripple.set(true);
    this.primeng.setTranslation({
      apply: 'Aplicar',
      clear: 'Limpar',
      accept: 'Sim',
      reject: 'Não',
      firstDayOfWeek: 0,
      dayNames: [
        'Domingo',
        'Segunda',
        'Terça',
        'Quarta',
        'Quinta',
        'Sexta',
        'Sábado',
      ],
      dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
      dayNamesMin: ['Do', 'Se', 'Te', 'Qu', 'Qu', 'Se', 'Sa'],
      monthNames: [
        'Janeiro',
        'Fevereiro',
        'Março',
        'Abril',
        'Maio',
        'Junho',
        'Julho',
        'Agosto',
        'Setembro',
        'Outubro',
        'Novembro',
        'Dezembro',
      ],
      monthNamesShort: [
        'Jan',
        'Fev',
        'Mar',
        'Abr',
        'Mai',
        'Jun',
        'Jul',
        'Ago',
        'Set',
        'Out',
        'Nov',
        'Dez',
      ],
      today: 'Hoje',
      strong: 'Forte',
      medium: 'Médio',
      weak: 'Fraco',
      passwordPrompt: 'Digite uma senha',
      emptyMessage: 'Nenhum resultado encontrado',
      emptySearchMessage: 'Nenhum resultado encontrado',
      emptySelectionMessage: 'Nenhum registro selecionado',
      emptyFilterMessage: 'Nenhum resultado encontrado',
      startsWith: 'Começa com',
      contains: 'Contém',
      notContains: 'Não contém',
      endsWith: 'Termina com',
      equals: 'Igual a',
      notEquals: 'Diferente de',
      noFilter: 'Sem filtro',
      lt: 'Menor que',
      lte: 'Menor ou igual a',
      gt: 'Maior que',
      gte: 'Maior ou igual a',
      dateIs: 'Data é',
      dateIsNot: 'Data não é',
      dateBefore: 'Data antes de',
      dateAfter: 'Data depois de',
      matchAll: 'Corresponder a todos',
      matchAny: 'Corresponder a qualquer',
      addRule: 'Adicionar regra',
      removeRule: 'Remover regra',
      choose: 'Escolher',
      upload: 'Upload',
      cancel: 'Cancelar',
      pending: 'Pendente',
      fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
      chooseYear: 'Escolher ano',
      chooseMonth: 'Escolher mês',
      chooseDate: 'Escolher data',
      prevDecade: 'Década anterior',
      nextDecade: 'Próxima década',
      prevYear: 'Ano anterior',
      nextYear: 'Próximo ano',
      prevMonth: 'Mês anterior',
      nextMonth: 'Próximo mês',
      prevHour: 'Hora anterior',
      nextHour: 'Próxima hora',
      prevMinute: 'Minuto anterior',
      nextMinute: 'Próximo minuto',
      prevSecond: 'Segundo anterior',
      nextSecond: 'Próximo segundo',
      am: 'am',
      pm: 'pm',
      weekHeader: 'Sem',
      dateFormat: 'dd/mm/yy',

      searchMessage: '{0} resultados disponíveis',
      selectionMessage: '{0} itens selecionados',

      aria: {
        trueLabel: 'Verdadeiro',
        falseLabel: 'Falso',
        nullLabel: 'Não selecionado',
        star: '1 estrela',
        stars: '{star} estrelas',
        selectAll: 'Todos os itens selecionados',
        unselectAll: 'Todos os itens desmarcados',
        close: 'Fechar',
        previous: 'Anterior',
        next: 'Próximo',
        navigation: 'Navegação',
        scrollTop: 'Rolar para o topo',
        moveTop: 'Mover para o topo',
        moveUp: 'Mover para cima',
        moveDown: 'Mover para baixo',
        moveBottom: 'Mover para o fim',
        moveToTarget: 'Mover para o destino',
        moveToSource: 'Mover para a origem',
        moveAllToTarget: 'Mover todos para o destino',
        moveAllToSource: 'Mover todos para a origem',
        pageLabel: '{page}',
        firstPageLabel: 'Primeira página',
        lastPageLabel: 'Última página',
        nextPageLabel: 'Próxima página',
        prevPageLabel: 'Página anterior',
        rowsPerPageLabel: 'Linhas por página',
        jumpToPageDropdownLabel: 'Ir para página (menu)',
        jumpToPageInputLabel: 'Ir para página (entrada)',
        selectRow: 'Linha selecionada',
        unselectRow: 'Linha desmarcada',
        expandRow: 'Linha expandida',
        collapseRow: 'Linha recolhida',
        showFilterMenu: 'Mostrar menu de filtro',
        hideFilterMenu: 'Ocultar menu de filtro',
        filterOperator: 'Operador de filtro',
        filterConstraint: 'Restrição de filtro',
        editRow: 'Editar linha',
        saveEdit: 'Salvar edição',
        cancelEdit: 'Cancelar edição',
        listView: 'Modo lista',
        gridView: 'Modo grade',
        slide: 'Slide',
        slideNumber: '{slideNumber}',
        zoomImage: 'Ampliar imagem',
        zoomIn: 'Aumentar zoom',
        zoomOut: 'Reduzir zoom',
        rotateRight: 'Girar para a direita',
        rotateLeft: 'Girar para a esquerda',
      },
    });
  }
}
